framework:
    default_locale: de_CH
    enabled_locales: ['en_US', 'uk_UA']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
